import { Bell, CheckCheck } from "lucide-react";

import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { ModuleBoundary } from "../components/ui/ModuleBoundary";
import { SectionPanel } from "../components/ui/SectionPanel";
import type { ModulePageProps } from "../types/page";
import { formatTime } from "../utils/format";

export function NotificationsPage({ data, selectedCompany, isLoadingModules, moduleError, onRetry }: ModulePageProps): JSX.Element {
  return (
    <SectionPanel
      eyebrow={selectedCompany?.name ?? "Action stream"}
      title="Notifications"
      action={<Button disabled icon={<CheckCheck className="size-4" aria-hidden="true" />}>Mark all read</Button>}
    >
      <ModuleBoundary
        emptyDescription="Notifications generated by work assignments, leave requests, and system events will appear here."
        emptyTitle="No notifications yet"
        error={moduleError}
        isEmpty={data.notifications.length === 0}
        isLoading={isLoadingModules}
        onRetry={onRetry}
      >
        <div className="divide-y divide-grid-100">
          {data.notifications.map((notification) => (
            <article key={notification.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex min-w-0 items-start gap-3">
                <span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-grid-100 text-ink-700">
                  <Bell className="size-4" aria-hidden="true" />
                </span>
                <div className="min-w-0">
                  <p className="truncate text-sm font-bold text-ink-950">{notification.title}</p>
                  <p className="mt-1 line-clamp-2 text-sm text-ink-500">{notification.message}</p>
                  <p className="mt-1 text-xs font-semibold text-ink-500">{formatTime(notification.created_at)}</p>
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <Badge label={notification.notification_type} tone="blue" />
                <Badge label={notification.is_read ? "Read" : "Open"} tone={notification.is_read ? "slate" : "amber"} />
              </div>
            </article>
          ))}
        </div>
      </ModuleBoundary>
    </SectionPanel>
  );
}
