from fastapi import APIRouter

from app.api.routes import (
    attachments,
    auth,
    ai_jobs,
    billing,
    companies,
    company_memory,
    company_pulse,
    configuration,
    communication,
    dashboard,
    departments,
    employee_digital_twin,
    employees,
    events,
    health,
    invitations,
    leaves,
    notifications,
    projects,
    search,
    teams,
    work_dna,
    work_objects,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(billing.router)
api_router.include_router(companies.router)
api_router.include_router(configuration.settings_router)
api_router.include_router(configuration.templates_router)
api_router.include_router(configuration.work_object_types_router)
api_router.include_router(configuration.custom_fields_router)
api_router.include_router(dashboard.router)
api_router.include_router(departments.router)
api_router.include_router(employees.router)
api_router.include_router(employee_digital_twin.router)
api_router.include_router(invitations.router)
api_router.include_router(teams.router)
api_router.include_router(projects.router)
api_router.include_router(work_objects.router)
api_router.include_router(communication.comments_router)
api_router.include_router(communication.announcements_router)
api_router.include_router(leaves.router)
api_router.include_router(leaves.employee_router)
api_router.include_router(attachments.router)
api_router.include_router(attachments.uploads_router)
api_router.include_router(attachments.files_router)
api_router.include_router(events.router)
api_router.include_router(events.timeline_router)
api_router.include_router(events.audit_router)
api_router.include_router(notifications.router)
api_router.include_router(ai_jobs.router)
api_router.include_router(ai_jobs.legacy_router)
api_router.include_router(company_memory.router)
api_router.include_router(company_pulse.router)
api_router.include_router(work_dna.router)
api_router.include_router(search.router)
